version: 0.2

env:
  shell: bash
  variables:
    SHELL: /bin/bash
    AWS_DEFAULT_REGION: eu-central-1
    USER: "aws_code_build"
    ENV: "dev"
    PIPENV_NOSPIN: 1

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "Installing different python versions"
      - apt-get update -qq
      - apt-get install -yqq python3-pip python3.8 python3.9
  build:
    commands:
      - echo "Setting up dev mode with python version $(python --version)..."
      - pip install --upgrade pip
      - pip install -r dev_requirements.txt
      - pip install -e .
      - echo "Running nose tests..."
      - nose2 -v -s tests/
      - echo "Setting up dev mode python python version $(python3.8 --version)..."
      - python3.8 -m pip install --upgrade pip
      - python3.8 -m pip install -r dev_requirements.txt
      - python3.8 -m pip install -e .
      - echo "Running nose tests..."
      - python3.8 -m nose2 -v -s tests/
      - echo "Setting up dev mode python python version $(python3.9 --version)..."
      - python3.9 -m pip install --upgrade pip
      - python3.9 -m pip install -r dev_requirements.txt
      - python3.9 -m pip install -e .
      - echo "Running nose tests..."
      - python3.9 -m nose2 -v -s tests/
